// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass<T0, T1> where T0 : unmanaged, global::System.IEquatable<T1> where T1 : unmanaged, global::System.IEquatable<T0>
    {
        bool TestGenericMethod(T0 arg0, T1 arg1);
    }
}