// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass
    {
        bool TestGenericMethod0<T>(T arg0, T arg1) where T : unmanaged, global::System.IEquatable<T>;
        bool TestGenericMethod1<T>(T arg0, T arg1) where T : notnull, global::System.IEquatable<T>, new();
        bool TestGenericMethod2<T>(T arg0, T arg1) where T : class, global::System.IEquatable<T>, new();
        bool TestGenericMethod3<T>(T arg0, T arg1) where T : struct, global::System.IEquatable<T>;
    }
}