// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass<T0, T1>
    {
        T0 Property1 { get; set; }
        T1 Property2 { get; set; }
        (T0, T1) GenericMethod(T0 arg0, T1 arg1);
    }
}