// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass
    {
        int Property1 { get; set; }
        int Property2 { get; }
        int Property3 { set; }
        int Property4 { get; }
        string Property5 { get; init; }
        float Property6 { get; }
    }
}