// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass
    {
        bool TestGenericMethod0<T0, T1>(T0 arg0, T1 arg1) where T0 : unmanaged, global::System.IEquatable<T1> where T1 : unmanaged, global::System.IEquatable<T0>;
        bool TestGenericMethod1<T0, T1>(T0 arg0, T1 arg1) where T0 : notnull, global::System.IEquatable<T1> where T1 : class, global::System.IEquatable<T0>, new();
        bool TestGenericMethod2<T0, T1>(T0 arg0, T1 arg1) where T0 : struct, global::System.IEquatable<T1> where T1 : notnull, global::System.IEquatable<T0>, new();
    }
}