// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace.SubNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface IExampleInterface
    {
    }
}