// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// Timestamp: {Removed}
// </auto-generated>
namespace global::TestNamespace
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass
    {
        void Method1();
        int Method2(int arg);
        float Method3(float arg1, float arg2);
    }
}