//HintName: ITestClass.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// </auto-generated>
using System;
using Minerals.AutoInterfaces;

namespace Minerals.Examples
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass
    {
        void Method1();
        void Method2(int arg);
        int Method3();
        int Method4(int arg);
    }
}