//HintName: GenerateInterfaceAttribute.g.cs
// <auto-generated />

namespace Minerals.AutoInterfaces
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class GenerateInterfaceAttribute : global::System.Attribute
    {
    }
}