//HintName: ITestClass.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoInterfaces
// Version: {Removed}
// </auto-generated>
using System;
using Minerals.AutoInterfaces;

namespace Minerals.Examples
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public interface ITestClass
    {
        int Property1 { get; set; }
        int Property2 { get; set; }
        float Property3 { get; set; }
    }
}