//HintName: ITestClass.g.cs
// <auto-generated />

using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;

namespace Minerals.AutoInterfaces.Tests
{
    public interface ITestClass
    {
        public void Method1();
        public void Method2(int arg);
        public int Method3();
        public int Method4(int arg);
    }
}