//HintName: ITestClass.g.cs
// <auto-generated />

using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;

namespace Minerals.AutoInterfaces.Tests
{
    public interface ITestClass
    {
        public int Property1 { get; set; }
        public int Property2 { get; }
        public int Property3 { set; }
        public int Property4 { get; }
        public string Property5 { get; init; }
        public float Property6 { get; }
    }
}