//HintName: ITestClass.g.cs
// <auto-generated />

using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;

namespace Minerals.AutoInterfaces.Tests
{
    public interface ITestClass
    {
        public event EventHandler? Event1;
        public event Action<int>? Event2;
    }
}