namespace Minerals.AutoInterfaces
{
    [Generator]
    public class GenerateAttributeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("GenerateInterfaceAttribute.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            // <auto-generated />

            namespace Minerals.AutoInterfaces
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class GenerateInterfaceAttribute : global::System.Attribute
                {
            
                }
            }
            """;
            return SourceText.From(source, Encoding.UTF8);
        }
    }
}