namespace Minerals.AutoInterfaces.Utilities
{
    public static class CodeBuilderlExtensions
    {
        public static CodeBuilder AppendAutoGeneratedHeader(this CodeBuilder builder)
        {
            var name = typeof(CodeBuilderlExtensions).Assembly.GetName().Name;
            var version = typeof(CodeBuilderlExtensions).Assembly.GetName().Version;
            var timestamp = DateTime.Now.ToString("yyyy.MM.dd HH:mm:ss");

            builder.Write("// <auto-generated>");
            builder.WriteLine("// This code was generated by a tool.");
            builder.WriteLine($"// Name: {name}");
            builder.WriteLine($"// Version: {version}");
            builder.WriteLine($"// Timestamp: {timestamp}");
            builder.WriteLine("// </auto-generated>");

            return builder;
        }

        public static CodeBuilder AppendAutoGeneratedAttributes(this CodeBuilder builder, bool isInterface)
        {
            if (!isInterface)
            {
                builder.WriteLine("[global::System.Diagnostics.DebuggerNonUserCode]");
                builder.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            }
            builder.WriteLine("[global::System.Runtime.CompilerServices.CompilerGenerated]");
            return builder;
        }
    }
}